### PR TITLE
[WIP] Feature/updated dockerfile prelanding

### PR DESCRIPTION
**Pull request by AlvaroVega**

### CODE REVIEW

**Comment by fgalan** [comment]
@cblanco we have experiencing some problems with the changes included in the PR in our e2e integration suite. Around 40 cases related with perseo are passing. We have created this PR (in WIP status) to debug the case.

Keep tuned :)

**Comment by fgalan** [comment]
I have been able to catch Perseo Core logs at the end and I see this error message:

```
time=2018-10-16T09:58:56.489Z | lvl=ERROR | from=... | corr=18716e2c-d12a-11e8-a9d9-0242ac110011; perseocep=16 | trans=54d981dc-c509-43cf-8a09-42a6d8e76d08 | srv=cb0010302 | subsrv=/sscb002cep | op=DoHTTPPost | comp=perseo-core | msg=exception MalformedURLException: java.net.MalformedURLException
time=2018-10-16T09:58:56.489Z | lvl=ERROR | from=... | corr=18716e2c-d12a-11e8-a9d9-0242ac110011; perseocep=16 | trans=54d981dc-c509-43cf-8a09-42a6d8e76d08 | srv=cb0010302 | subsrv=/sscb002cep | op=update | comp=perseo-core | msg=action post failed
```

So maybe something is failing in the Perseo FE URL build process changed by this PR...

**Comment by fgalan** [comment]
This error trace is also printed by Perseo Core at startup

```
time=2018-10-16T11:19:41.644Z | lvl=ERROR | from=172.17.0.13 | corr=n/a | trans=a5fca4d4-c4b5-40fd-8f26-4808cda30190 | srv=n/a | subsrv=n/a | op=reload | comp=perseo-core | msg=Invalid value for PERSEO_FE_URL: 172.17.0.1:19090
```

We are getting closer... ;)

**Comment by fgalan** [comment]
Finally, I think I know what is going on.

Perseo Core is run as a docker managed by docker compose. The section in docker-compose.yml corresponding to it is using this:

```
command: -perseo_fe_url 172.17.0.1:19090
```

However, the changes in Configuration class included in this PR now detect that as an invalid URL due to the `http://` prefix is missing.

Being strict is good... but not so strict that could break existing deployments like this one :) Thus, there are two possible soluctions, from my point of view:

1. Adjust the URL in perseo_core-entrypoint.sh. That is, if the `-perseo_fe_url` parameters doesn't start by `http` or `https` then add `http://`.
2. Adjust the URL in Configuration class. The same: if the URL doesn't start by `http` or `https` then add `http://`.

I think is better approach 2, due to:

1. The above checking/adaptation uses to be easier to implement in Java than in bash
2. Approach 2 will support both the cases in which the URL is provided by env var to the docker or by `-perseo_fe_url` param to the entry point. Approach 1 will only support the former.

What do you think @cblanco ? Could you do the fix (as a new PR to feature/updatedDockerfile-prelanding branch), pleases? Thanks!

**Comment by cblanco** [comment]
I agree with your solution.

Yes, I will do the correction for this problem soon.

Thanks for the analysis!

**Comment by fgalan** [comment]
Apart from the above, I have realized the following fact:

imagen

"latest" is docker image built from master branch (i.e. CentOS7-based image) while "prelanding" is a docker image built from this branch (i.e. Tomcat-based image). It had supposed that Tomcat-based image build should be smaller, as the image is much more focused... however is 100MB larger. 

Maybe Dockerfile in this branch needs some cleaning step (mvn clean, apt-get clean, etc.)? Or this is a normal an expected situation?

**Comment by cblanco** [comment]
Yeah, you are right, we can lighten up the image. Our first approach was to change the image to use the official tomcat image of tomcat to gain maintenance and security support of that part from the Docker community. Take into account that currently, the Dockerfile is copying the source code into the image and it is installing the tools for building it. This is not efficient, but it is the behaviour inherited from the previous `Dockerfile`. We should analyse the different options we have to change this. Maybe we could clean the unused files and packages now and consider changing /optimizing the image in a future PR.

What do you think?

**Comment by fgalan** [comment]
I think that a more detailed anaylis of this could be done in a separate PR but maybe easy actions can be included in the Dockefiles. For instance:

```
  mvn clean && \ (don't remember if this target exist in mvn...)
  apt-get clean && \
  apt-get remove -y maven && \ (as once the project is build maven is not needed any longer)
  apt-get -y autoremove
```

In addition, not sure but I think that maven uses a `.m2/` directory for cache of packages. Maybe it should be also removed (`rm .m2`).

**Comment by cblanco** [comment]
Ok. The new PR is ready.

I have not found any .m2 folder in the image and I have remove the source code directory and /var/lib/apt/lists/* files too.

**Comment by fgalan** [comment]
imagen

It seems image has reduced a bit (15MB) but not enough to be comparable to the one generated with the old Dockerfile.

Anyway, I think it's fine by the moment. We will test the new docker in the e2e testing environment, so see how it goes.

**Comment by cblanco** [comment]
In this version of the Dockerfile we are generating the war from the source code. If I'm not wrong, we need the java compiler when we execute mvn dependency:resolve and also in the package, so I think we need javac, that as far as I know, it is not included in the jre, only in the jdk.

**Comment by fgalan** [comment]
> In this version of the Dockerfile we are generating the war from the source code. If I'm not wrong, we need the java compiler when we execute mvn dependency:resolve and also in the package, so I think we need javac, that as far as I know, it is not included in the jre, only in the jdk.

In that case, I undertand that once the package has been built, the JDK can be removed (I mean, apt-get remove after the mvn command to build) and replaced by the JRE.

In fact, maybe the base image already includes a default JRE? Being a tomcat image, I tend to thinkg so... but not sure.

**Comment by cblanco** [comment]
Yes, I have done some tests and it seems that it is not necessary to install the JRE. It must be included in the Tomcat image. 👍 

On the other hand, I think we can also reduce the size a little if we use a single RUN.

Now I will create another PR with the changes and so you can consider if they are correct.

**Comment by fgalan** [comment]
After merging PR #109

imagen

That is a 62 MB reduction since last one. Maybe new optimization are possible, to get even closer to 197 MB of the current lastest, but I wouldn't delay this PR for that.

**Comment by fgalan** [comment]
e2e integration testing seems to work with the current image in this PR, so we are mergin into master.

Thanks @cblanco for your work!

**Pull request merged**
